apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-in-memory-env
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: in-memory-env
    functionRef:
      name: function-in-memory-env